2025-03-11 09:45:08,892 - app - INFO - Welcome to formsflow-API server...! (app.py:67)
2025-03-11 09:45:10,489 - app - DEBUG - JWT MANAGER running in test mode, using locally defined certs & tokens (jwt_manager.py:79)
2025-03-11 09:45:10,489 - app - DEBUG - local key being used: {'keys': [{'kid': 'forms-flow-web', 'kty': 'RSA', 'alg': 'RS256', 'use': 'sig', 'n': 'AN-fWcpCyE5KPzHDjigLaSUVZI0uYrcGcc40InVtl-rQRDmAh-C2W8H4_Hxhr5VLc6crsJ2LiJTV_E72S03pzpOOaaYV6-TzAjCou2GYJIXev7f6Hh512PuG5wyxda_TlBSsI-gvphRTPsKCnPutrbiukCYrnPuWxX5_cES9eStR', 'e': 'AQAB'}]} (jwt_manager.py:93)
2025-03-11 09:45:10,489 - app - DEBUG - JWKS_URI: None (jwt_manager.py:134)
2025-03-11 09:45:10,489 - app - DEBUG - ISSUER: http://192.168.1.72:8080/auth/realms/forms-flow-ai (jwt_manager.py:135)
2025-03-11 09:45:10,489 - app - DEBUG - ALGORITHMS: RS256 (jwt_manager.py:136)
2025-03-11 09:45:10,489 - app - DEBUG - AUDIENCE: forms-flow-web (jwt_manager.py:137)
2025-03-11 09:45:10,489 - app - DEBUG - CLIENT_SECRET: None (jwt_manager.py:138)
2025-03-11 09:45:10,489 - app - DEBUG - JWT_OIDC_TEST_MODE: True (jwt_manager.py:139)
2025-03-11 09:45:10,489 - app - DEBUG - JWT_OIDC_TEST_KEYS: {'keys': [{'kid': 'forms-flow-web', 'kty': 'RSA', 'alg': 'RS256', 'use': 'sig', 'n': 'AN-fWcpCyE5KPzHDjigLaSUVZI0uYrcGcc40InVtl-rQRDmAh-C2W8H4_Hxhr5VLc6crsJ2LiJTV_E72S03pzpOOaaYV6-TzAjCou2GYJIXev7f6Hh512PuG5wyxda_TlBSsI-gvphRTPsKCnPutrbiukCYrnPuWxX5_cES9eStR', 'e': 'AQAB'}]} (jwt_manager.py:140)
2025-03-11 09:45:10,489 - app - INFO - Establishing new connection to formio... (startup.py:30)
2025-03-11 09:45:10,490 - app - INFO - Redis client initiated successfully (caching.py:41)
2025-03-11 09:45:10,503 - app - ERROR - Error 61 connecting to localhost:6379. Connection refused. (startup.py:44)
2025-03-11 09:45:10,503 - app - INFO - Fetching user resource ids... (formio.py:105)
2025-03-11 09:45:11,851 - app - ERROR - Error 61 connecting to localhost:6379. Connection refused. (startup.py:60)
